### PR TITLE
Location class called use a diferent called way of the current docume…

### PR DESCRIPTION
**Pull request by tmendes-ciandt**
Location class called use a diferent called way of the current documentation, i don't tested the others methods for now, sounds like works fine, if i have been doing something wrong please tell me

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the pull request Thiago! It should work as before. The only difference being that `if` is now called `where` and both methods on the location class now has `static` as return type. Is it not working on your end?

**Comment by tmendes-ciandt** [comment]
So, i tested using `Location::where('post_type', 'page');` but don't worked, and then i tested with `new Location('post_type', '==', 'post');` and works fine, i don't know why...

Taking advantage, I would like to add to my group fields to use the WP Metabox style... i don't find in the document how can i using with this way... can you help me? I was think i something like this `'style' => 'default'`, i'm right?

**Comment by vinkla** [comment]
Are you using the latest version of this package? What error message are you seeing?

**Comment by tmendes-ciandt** [comment]
My version is 11.2 and show the error:

```  Call to undefined method WordPlate\Acf\Location::where() ``` 

Looking on `wordplate\acf\src\Location.php` i saw that the where method doesn't exist...  i undestand now the problem, my project use `PHP 7.4`... and the version 12 needs to use `PHP8` right? So i think that we can close this PR, i did a fork i hope can help in the future!

**Comment by vinkla** [comment]
If you're using version 11 you'll need to use the `if` method instead of `where`. We renamed it in version 12.

**Comment by bramchi** [comment]
Thanks for clearing that up!

I encountered the same small confusion with version 11 being installed by default because of my PHP 7.4 and therefore the Usage snippet not working of the box. A small pointer about version 11 vs 12 wouldn't hurt for new users in the readme I think.

**Comment by vinkla** [comment]
[It is in the documentation.](https://github.com/wordplate/extended-acf#location)

> A small pointer about version 11 vs 12 wouldn't hurt for new users in the readme I think.

This is what PRs are for.

**Comment by bramchi** [comment]
You're right, RTFM! 

[Here's a PR to help my future self and others](https://github.com/wordplate/extended-acf/pull/110).

Thank for the great class, it does everything I dreamed of. 
If you ask me, this stuff should be part of the original ACF!

**Comment by vinkla** [comment]
> Here's a PR to help my future self and others.

Great work 👏 

> Thank for the great class, it does everything I dreamed of.
> If you ask me, this stuff should be part of the original ACF!

I'm glad you like it 😊

**Pull request closed without merging**
