### PR TITLE
feat: add disable trait

### PR DESCRIPTION
**Pull request by zangab**
Adds a disable trait to disallow any user input on the admin interface

## Proposed Changes

  - disable trait
  - should be used on all fields (TODO)

### CODE REVIEW

**Comment by vinkla** [comment]
Great work @zangab! I didn't even know about the `disabled` attribute existed. Do you know where I can find documentation on the `disabled` and `readonly` settings?

**Comment by vinkla** [comment]
Just tried this locally and seems to work fine. If you want to, please add a second pull request for the `readonly` attribute with `ReadOnly` trait.

**Comment by zangab** [comment]
@vinkla 
don't know if this is officially documented somewhere, but it's in some stackoverflow threads and it was quite handy sometimes. the disable should work on all fields. sure, i will do another PR for the readonly. 🤓

**Comment by vinkla** [comment]
It seems they aren't supported on all fields and they are working on updates for the next release:

https://twitter.com/wp_acf/status/1288358105080713217?s=20

**Comment by vinkla** [comment]
Before we add this feature we need to figure out which fields actually supports the `disabled` attribute.

Maybe we could as @elliotcondon?

**Comment by elliotcondon** [comment]
Hi @vinkla 👋

The "disabled" setting is not yet fully supported across all our Field Types, however, I can confirm that this is something I am hoping to address in an upcoming release - most likely 5.10.

The Field Types that currently support the "disabled" property are:
- Checkbox
- Date Picker
- Email
- Number
- Radio Buttons
- Range
- Select
- Text
- Textarea
- URL

**Comment by vinkla** [comment]
Thanks for getting back @elliotcondon. Looking forward to read the 5.10 beta changelog 🙌 

Then we'll add the supported fields for now and revisit this once 5.10 beta is realsed.

**Comment by vinkla** [comment]
This has now been merged. Thanks @zangab and @elliotcondon!

**Pull request merged**
