### PR TITLE
Added layout to checkbox field

### PR DESCRIPTION
**Pull request by jbbouchet**
Add new method on Checkbox to set layout. (Maybe it can be confused with layout Trait, but values are differents)

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the pull request @jbbouchet 🙌 

Could you please add a test for the new configuration to the `CheckboxTest` class?

> Maybe it can be confused with layout Trait, but values are differents.

Since it is named "Layout" in the administrator dashboard I think it is fine.

**Comment by jbbouchet** [comment]
Of course i do

**Comment by vinkla** [comment]
Please update the test to look similar to this:

https://github.com/wordplate/extended-acf/blob/6b16b3e32fbcf87ba2cb27ea9c76065bc3f76595/tests/Fields/GroupTest.php#L40-L48

**Comment by jbbouchet** [comment]
> Please update the test to look similar to the test below (using only one test case).
> 
> https://github.com/wordplate/extended-acf/blob/6b16b3e32fbcf87ba2cb27ea9c76065bc3f76595/tests/Fields/GroupTest.php#L40-L49

Oh i'm sorry, i didn't see.

**Comment by vinkla** [comment]
Thanks!

**Pull request merged**
