### PR TITLE
Adds customConfig method in Field

### PR DESCRIPTION
**Pull request by guicapanema**
Hi there!

So, today I came across [a plugin](https://github.com/mcguffin/acf-quickedit-fields) which allows quick and bulk editing ACF fields. It uses custom config keys inside each field to enable/disable the quick/bulk editing behaviour.

When looking through Extended ACF, I couldn't find a way of setting these one-off config keys. Since I will use them in a single field, I wouldn't like to extend a class just for this one case.

So I'm proposing adding a `customConfig` method to the core `Field` class, which allows manually setting a config key/value pair.

Sample usage:

```
Select::make('Test field')
    ->customConfig('allow_bulkedit', 1)
    ->customConfig('allow_quickedit', 1),
```

Cheers!

### CODE REVIEW

**Comment by vinkla** [comment]
Thanks for the pull request Guilherme!

I do understand what you're trying to achieve but I'm not sure this is the solution. It is already possible to extend the existing fields like any other PHP class:

```php
use WordPlate\Acf\Fields\Select as Field;

class Select extends Field
{
	public function myKey($value)
	{
		$this->config->set('my-key, $value);

		return $this;
	}
}

```

I like your idea but for now I think extending existing fields is the way to go. We might revisit this in the future.

**Comment by vinkla** [comment]
[I've added this to the documentation.](https://github.com/wordplate/extended-acf#custom-configuration)

**Comment by guicapanema** [comment]
Hi, Vincent!

I do understand we can already extend the field classes to add this behaviour, but it seems a bit heavy handed to me for a behaviour which I, personally, expected to be available as a core option.

Also, there's a possible scenario where you'd like to set a custom config key in multiple field types and you'd need to extend each one of them and add the same function multiple times, which feels nonoptimal.

Those are just my opinions, though, so I'm totally fine if you still think that's the way to go.

Cheers!

**Comment by guicapanema** [comment]
PS: just saw this is similar to what's been previously discussed in #44 and PR'd in #48 , so I'm sorry for bringing this up as a new PR.

**Comment by vinkla** [comment]
Thanks for the comments. I'll keep this in mind for future releases. If we were to add it we need to find a good and straight forward naming convention.

**Pull request closed without merging**
